# Generated by Django 3.0.5 on 2020-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200623_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
