# Generated by Django 3.0.5 on 2020-06-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200623_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='time',
            new_name='greenTime',
        ),
    ]
