# Generated by Django 3.0.5 on 2020-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200623_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlight',
            name='yellowTime',
            field=models.FloatField(default=0),
        ),
    ]
