# Generated by Django 3.0.5 on 2020-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sn',
            field=models.IntegerField(default=1),
        ),
    ]
