# Generated by Django 3.0.5 on 2020-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_currentimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='white', max_length=20)),
                ('sn', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0)),
            ],
        ),
    ]
