# Generated by Django 3.0.5 on 2020-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trafficlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
