# Generated by Django 3.0.5 on 2020-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_trafficlight_yellowtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentimages',
            name='programStarted',
            field=models.BooleanField(default=False),
        ),
    ]
