# Generated by Django 3.0.5 on 2020-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trafficlight_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='sn',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='emergency',
            field=models.BooleanField(default=True),
        ),
    ]
