# Generated by Django 3.0.5 on 2020-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200625_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentimages',
            name='id',
        ),
        migrations.AddField(
            model_name='currentimages',
            name='sn',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
