# Generated by Django 3.0.5 on 2020-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200625_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentimages',
            name='img0',
            field=models.CharField(default='img0', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentimages',
            name='img1',
            field=models.CharField(default='img1', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentimages',
            name='img2',
            field=models.CharField(default='img2', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentimages',
            name='img3',
            field=models.CharField(default='img3', max_length=50),
        ),
    ]
